### ISSUE TITLE
Online database not working

### ISSUE THREAD

**Issue by Strawsine2020** [UMNFuN/FUNGuild#37] opened 2020-12-13 21:19 UTC
Hi,

I've used the online database in the past, but am having issues trying to use it today. Every search doesn't produce results. I'm wondering if I should install a local copy and run that instead, but am wondering if it's the database itself? Any ideas?

Thank you!

**Comment by ZeweiSong** [comment] 2020-12-15 08:53
Please check issue #38 for the solution.
Duplicate of #38

**Closed as completed** 2020-12-15 09:05 UTC
